# Generated by Django 4.1.7 on 2023-05-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fromula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAT_NO', models.TextField()),
                ('Chemical_name', models.TextField()),
                ('Molecular_Formula', models.TextField()),
                ('Molecular_Weight', models.IntegerField()),
                ('CAS_Number', models.TextField()),
                ('Solubility', models.TextField()),
                ('Storage', models.TextField()),
                ('Keywords', models.TextField()),
                ('Purity_by_HPLC', models.TextField()),
                ('Inventory_status', models.TextField()),
            ],
        ),
    ]
