# Generated by Django 4.1.7 on 2023-06-01 09:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fromula',
            name='image',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fromula',
            name='CAS_Number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='fromula',
            name='CAT_NO',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='fromula',
            name='Chemical_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fromula',
            name='Inventory_status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='fromula',
            name='Keywords',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='fromula',
            name='Molecular_Formula',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='fromula',
            name='Purity_by_HPLC',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='fromula',
            name='Solubility',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='fromula',
            name='Storage',
            field=models.CharField(max_length=40),
        ),
    ]
