# Generated by Django 4.1.7 on 2023-06-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_fromula_image_alter_fromula_cas_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fromula',
            name='Product_name',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
