# Generated by Django 4.1.7 on 2023-06-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_fromula_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Message', models.TextField(max_length=500)),
            ],
        ),
    ]
