# Generated by Django 4.1.7 on 2023-06-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='Product_name',
            field=models.CharField(max_length=500),
        ),
    ]
